# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24643a3e4de764d718a1718c292e60346ee2e72f8e4996f8a783d2f5827fbfb0dc6dd204e6075a51468addb8f0b96c3f69cb647534aad43a9389bf5f2eff331d

test:
  secret_key_base: 593e3d33f89596a09a46b86318a14ed91dd3c30fc157b8ec094642d4921eed58da2f6321ee2ca30f108e963fd370e8f04c370bfc0ca594e17100bfe3c80a0515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
